steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tensile-pier-345417/hi-sas:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/tensile-pier-345417/hi-sas:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'hi-sas'
  - '--image'
  - 'gcr.io/tensile-pier-345417/hi-sas:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'
  - '--allow-unauthenticated'
images:
- 'gcr.io/tensile-pier-345417/hi-sas:$COMMIT_SHA'
