version: '3.9'

services:
  hello:
    container_name: 'prj_hello_sas'
    ports:
      - target: 80
        published: 8000
        mode: host
    volumes:
      - type: bind
        source: ./src
        target: /src
    build:
      context: .
    environment:
      APP_ENV: development
    networks:
      - sas-hello-net
    stdin_open: true
networks:
  sas-hello-net:
    name: sas-hello-net
    driver: bridge